### ISSUE TITLE
nlog.config not found when restarting webapp container

### ISSUE THREAD

**Issue by xme** [docintelapp/DocIntel#17]
My /config is properly mapped in docker-compose.yml.
nlog.config exists...permissions are correct...
I get this when starting webapp:
```
Unhandled exception. System.IO.FileNotFoundException: nlog.config
   at DocIntel.WebApp.Program.Main(String[] args) in /src/DocIntel.WebApp/Program.cs:line 44
```
I tried to stop/start manually the container, problem remains the same.

**Comment by xme** [comment]
The problem arised after I recompiled from source. I did a quick check in the code and applied this workaround. 
Added a new mapping in the docker-compose:
`      - /data/docintel/config:/etc/docintel
`
Now, webapp successfully started...

**Comment by ancailliau** [comment]
Are you binding the volume `/config`? Can you share your docker-compose file?  

```
webapp:
    image: "docintelapp/webapp"
    container_name: docintel-dev-webapp
    ports:
      - 5005:80
    volumes:
      - _DOCINTEL_CONFIG_:/config
      - _DOCINTEL_DATA_/files/:/files
      - _DOCINTEL_DATA_/lock/:/lock
```
